#version: "3"

services:
    laravel-blog-markdown:
        image: "jhonoryza/laravel-blog-markdown:latest"
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - tunnel_default
            - redis_default

networks:
    tunnel_default:
        external: true
    redis_default:
        external: true
